{
	"version": 1685101646,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/walls.png",
		"images/tiledbackground.png",
		"images/spawner-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/enemy-sheet2.png",
		"images/enemywalk-sheet0.png",
		"images/enemywalk-sheet1.png",
		"images/sprite-sheet0.png",
		"images/arrow-sheet0.png",
		"images/hpbar-sheet0.png",
		"images/maxhpbar-sheet0.png",
		"images/playerhitbox-sheet0.png",
		"images/gem-sheet0.png",
		"images/gem-sheet1.png",
		"images/flail-sheet0.png",
		"images/targetshoot-sheet0.png",
		"images/enemycollision-sheet0.png",
		"images/pause_background-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/laserenemy-sheet0.png",
		"images/bloodsugar-sheet0.png",
		"images/bloodsugar-sheet1.png",
		"images/bloodsugar-sheet2.png",
		"images/bloodsugar2-sheet0.png",
		"images/hyperlimit-sheet0.png",
		"images/hypolimit-sheet0.png",
		"images/redfilter-sheet0.png",
		"images/bluefilter-sheet0.png",
		"images/sword-sheet0.png",
		"images/sword-sheet1.png",
		"images/sting-sheet0.png",
		"images/gempath-sheet0.png",
		"media/enemy-hitten.m4a",
		"media/enemy-hitten.ogg",
		"media/level-ip.m4a",
		"media/plasma-hit.m4a",
		"media/plasma-hit.ogg",
		"media/player-hitten.m4a",
		"media/player-hitten.ogg",
		"media/xp-gain.m4a",
		"media/xp-gain.ogg",
		"media/laser-shot.m4a",
		"media/[indie dance] - pylot - a race against time [monstercat release].m4a",
		"media/[indie dance] - pylot - a race against time [monstercat release].ogg",
		"media/shockone - light cycles.m4a",
		"media/shockone - light cycles.ogg",
		"media/glorious thunderzone.m4a",
		"media/glorious thunderzone.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}